/**
 * Retrieve external data.
 */

// Tile data
app.factory('tilesaw', ['$http', 'envConfig', function($http, config) {
  return { get: function(image) {
    return $http.get(config.tilesaw + image + '.tif', {cache: true}).then(function(result) { return result.data; })
  }}
}])

// Application content
app.factory('notes', ['$http', 'envConfig', 'miaThumbnailAdapter', '$sce', '$q', function($http, config, thumbs, $sce, $q) {
  window.miaThumbnailAdapter = thumbs // TODO: why isn't this injected below? I can't access inside either of the next functions on L15 and 16
  window.$q = $q // again, why!?
  return function() {
    var d = $q.defer()

    $http.get(config.crashpad, {cache: true}).then(function(result) {
      result.data.clusters = require('../clusters/clusters.json') // TODO: PS these shouldn't be hardcoded

      angular.forEach(result.data.objects, function(o) {
        o.thumbnail = miaThumbnailAdapter.get(o.views[0].image)
      })
      angular.forEach(result.data.panels, function(panel) {
        panel.trustedContent = $sce.trustAsHtml(panel.content)
      })

      return result.data;
    }).then(function(data) {
      // (artstories-image-dimensions.json is 72kb of JSON generated by a makefile task completely dependent on me)
      // TODO: compute this hash of image dimensions automatically, codify it into the image server.
      // then maybe serve up only the needed images?
      var url = "http://cdn.dx.artsmia.org/thumbs/artstories-image-dimensions.json"
      return $http.get(url).then(function(result) {
        var allImageDimensions = result.data
        data.objects = angular.forEach(data.objects, function(o, id) {
          var dimensions = allImageDimensions[o.views[0].image]
          if(!dimensions) return console.info('missing dimensions for', id, o.views[0].image)
          o.imageWidth = dimensions[0]
          o.imageHeight = dimensions[1]
        })

        d.resolve(data)
      })
    })

    return d.promise
  }
}])

app.factory('email', ['$http', 'envConfig', function($http, config) {
  return {
    share: function(email, params) {
      return $http.post(config.emailServer + email, params).success(function(response) {
        return response
      })
    }
  }
}])

app.factory('initIsotope', ['$rootScope', function($rootScope) {
  return function() {
    if( window.innerWidth < 1024 ) {
      return;
    }

    var cover = document.querySelector('#cover');

    this.iso = new Isotope( cover, {
      itemSelector:'.isotope-item',
      layoutMode:'masonryHorizontal',
      masonryHorizontal: {
        rowHeight: 300,
        gutter: 10
      },
      containerStyle: null,
      isInitLayout: false
    });

    var centerCover = function(){

      // Get height of container
      var availableHeight = $('.cover-wrapper').height();

      // Get number of rows - 300px plus 10px gutter.
      var rowCount = Math.floor( availableHeight / 310 ) || 1;

      // Get height that will wrap snugly around rows
      var newHeight = ( rowCount * 310 ) + 1;

      // Get new top for #cover
      var newTop = ( availableHeight - newHeight) / 2;

      // Update cover height and top margin
      $('#cover').css({
        'height': newHeight + 'px',
        'top': newTop + 'px'
      });

    }

    this.iso.on( 'layoutComplete', function(){

      centerCover();

      $('.cover-item').css({
        'opacity':1
      });

      $rootScope.loaded = true;

    });

    $(window).on( 'resize', function(){
      centerCover();
    });

    this.iso.layout();

  };
}])
